scan_timeout = 100

[conda]
ignore_base = false

[python]
detect_extensions = []
detect_files = []
format = 'via [ðŸ…¥ ${virtualenv} ]($style)'
python_binary = []

[package]
disabled = true

[git_status]
untracked = ''
ignore_submodules = true

[aws]
disabled = true

[pixi]
style = "#f9c405 bold"
detect_files = []
detect_folders = []
format = 'via [ðŸ…Ÿ ${environment} ]($style)'
